data:
  train_files: chamber111/VPPO_ViRL39K_train
  val_files: chamber111/VPPO_MMK12_validation
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 4096
  max_response_length: 2048
  rollout_batch_size: 384
  val_batch_size: 512
  format_prompt: examples/format_prompt/math_format_perception.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  max_pixels: 1003520 # 1280*28*28
  min_pixels: 200704 # 256*28*28
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: true
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: true 
  filter_key: accuracy
  filter_low: 0.01
  filter_high: 0.99 


worker:
  actor:
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    dynamic_batching: false
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 8
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16
      lr_warmup_ratio: 0.0
    fsdp:
      torch_dtype: bf16
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.9
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 1.0
      n: 8 # avg acc @ 8

  ref:
    dynamic_batching: false
    fsdp:
      torch_dtype: bf16
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: examples/reward_function/math.py

trainer:
  max_try_make_batch: -1
  total_epochs: 15
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_3b_math_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 2
  val_freq: 5  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 1  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null